-- Sample data for Appliance Tracker. Safe to paste into the Neon SQL editor.
-- Dates are relative to CURRENT_DATE so statuses stay correct whenever you run it.

-- 1) Starter labs
INSERT INTO labs (id, name, updated_at) VALUES (gen_random_uuid()::text, 'Invisalign', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO labs (id, name, updated_at) VALUES (gen_random_uuid()::text, 'AOA', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO labs (id, name, updated_at) VALUES (gen_random_uuid()::text, 'Vivera', now()) ON CONFLICT (name) DO NOTHING;
INSERT INTO labs (id, name, updated_at) VALUES (gen_random_uuid()::text, 'Angel Aligners', now()) ON CONFLICT (name) DO NOTHING;

-- 2) Sample appliances
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Henry', 'Adams', (SELECT id FROM labs WHERE name='Invisalign'), 'Space Maintainer', CURRENT_DATE - 18, CURRENT_DATE + 1, CURRENT_DATE - 2, NULL, 'Lab running behind.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Abigail', 'Roberts', (SELECT id FROM labs WHERE name='AOA'), 'Hawley Retainer', CURRENT_DATE - 19, CURRENT_DATE + 2, CURRENT_DATE - 3, NULL, 'Replacement for lost retainer.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Jack', 'Edwards', (SELECT id FROM labs WHERE name='Vivera'), 'Bonded Retainer', CURRENT_DATE - 10, CURRENT_DATE + 7, CURRENT_DATE + 2, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Aria', 'Morgan', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Nightguard', CURRENT_DATE - 11, CURRENT_DATE + 8, CURRENT_DATE, NULL, 'Refinement scan sent.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Carter', 'Smith', (SELECT id FROM labs WHERE name='Invisalign'), 'Herbst', CURRENT_DATE - 6, CURRENT_DATE + 22, CURRENT_DATE + 19, NULL, 'Confirm fit at delivery.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Nora', 'Thomas', (SELECT id FROM labs WHERE name='AOA'), 'Expander', CURRENT_DATE - 2, CURRENT_DATE + 23, CURRENT_DATE + 20, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'William', 'Walker', (SELECT id FROM labs WHERE name='Vivera'), 'Retainer', CURRENT_DATE - 3, CURRENT_DATE + 24, CURRENT_DATE + 21, NULL, 'Patient out of town until next week.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Charlotte', 'Baker', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Aligners', CURRENT_DATE - 21, CURRENT_DATE - 4, CURRENT_DATE - 8, CURRENT_DATE - 9, 'DD set for appt.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Daniel', 'Carter', (SELECT id FROM labs WHERE name='Invisalign'), 'Space Maintainer', CURRENT_DATE - 22, CURRENT_DATE - 5, CURRENT_DATE - 5, CURRENT_DATE - 7, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Sofia', 'Collins', (SELECT id FROM labs WHERE name='AOA'), 'Hawley Retainer', CURRENT_DATE - 27, CURRENT_DATE - 5, CURRENT_DATE - 9, CURRENT_DATE - 6, 'Followed up with lab.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Joseph', 'Rogers', (SELECT id FROM labs WHERE name='Vivera'), 'Bonded Retainer', CURRENT_DATE - 22, CURRENT_DATE + 2, CURRENT_DATE - 6, NULL, 'Rush case.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Camila', 'Garcia', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Nightguard', CURRENT_DATE - 23, CURRENT_DATE + 3, CURRENT_DATE - 7, NULL, 'Lab running behind.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Anthony', 'Anderson', (SELECT id FROM labs WHERE name='Invisalign'), 'Herbst', CURRENT_DATE - 8, CURRENT_DATE + 5, CURRENT_DATE, NULL, 'Replacement for lost retainer.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Ava', 'Robinson', (SELECT id FROM labs WHERE name='AOA'), 'Expander', CURRENT_DATE - 9, CURRENT_DATE + 6, CURRENT_DATE + 1, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Lucas', 'Green', (SELECT id FROM labs WHERE name='Vivera'), 'Retainer', CURRENT_DATE - 6, CURRENT_DATE + 20, CURRENT_DATE + 17, NULL, 'Refinement scan sent.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Evelyn', 'Mitchell', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Aligners', CURRENT_DATE - 2, CURRENT_DATE + 21, CURRENT_DATE + 18, NULL, 'Confirm fit at delivery.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Sebastian', 'Parker', (SELECT id FROM labs WHERE name='Invisalign'), 'Space Maintainer', CURRENT_DATE - 3, CURRENT_DATE + 22, CURRENT_DATE + 19, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Victoria', 'Cook', (SELECT id FROM labs WHERE name='AOA'), 'Hawley Retainer', CURRENT_DATE - 25, CURRENT_DATE - 4, CURRENT_DATE - 6, CURRENT_DATE - 8, 'Patient out of town until next week.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Wyatt', 'Johnson', (SELECT id FROM labs WHERE name='Vivera'), 'Bonded Retainer', CURRENT_DATE - 20, CURRENT_DATE - 5, CURRENT_DATE - 7, CURRENT_DATE - 7, 'DD set for appt.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Layla', 'Taylor', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Nightguard', CURRENT_DATE - 25, CURRENT_DATE - 7, CURRENT_DATE - 11, CURRENT_DATE - 6, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Noah', 'Lewis', (SELECT id FROM labs WHERE name='Invisalign'), 'Herbst', CURRENT_DATE - 20, CURRENT_DATE + 3, CURRENT_DATE - 4, NULL, 'Followed up with lab.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Mia', 'Scott', (SELECT id FROM labs WHERE name='AOA'), 'Expander', CURRENT_DATE - 21, CURRENT_DATE + 1, CURRENT_DATE - 5, NULL, 'Rush case.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Michael', 'Campbell', (SELECT id FROM labs WHERE name='Vivera'), 'Retainer', CURRENT_DATE - 10, CURRENT_DATE + 7, CURRENT_DATE + 1, NULL, 'Lab running behind.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Elizabeth', 'Torres', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Aligners', CURRENT_DATE - 11, CURRENT_DATE + 8, CURRENT_DATE + 2, NULL, 'Replacement for lost retainer.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Samuel', 'Murphy', (SELECT id FROM labs WHERE name='Invisalign'), 'Space Maintainer', CURRENT_DATE - 6, CURRENT_DATE + 18, CURRENT_DATE + 15, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Chloe', 'Nguyen', (SELECT id FROM labs WHERE name='AOA'), 'Hawley Retainer', CURRENT_DATE - 2, CURRENT_DATE + 19, CURRENT_DATE + 16, NULL, 'Refinement scan sent.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Gabriel', 'Moore', (SELECT id FROM labs WHERE name='Vivera'), 'Bonded Retainer', CURRENT_DATE - 3, CURRENT_DATE + 20, CURRENT_DATE + 17, NULL, 'Confirm fit at delivery.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Emma', 'Clark', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Nightguard', CURRENT_DATE - 23, CURRENT_DATE - 4, CURRENT_DATE - 8, CURRENT_DATE - 8, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Benjamin', 'Wright', (SELECT id FROM labs WHERE name='Invisalign'), 'Herbst', CURRENT_DATE - 24, CURRENT_DATE - 5, CURRENT_DATE - 5, CURRENT_DATE - 6, 'Patient out of town until next week.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Harper', 'Rivera', (SELECT id FROM labs WHERE name='AOA'), 'Expander', CURRENT_DATE - 29, CURRENT_DATE - 5, CURRENT_DATE - 9, CURRENT_DATE - 6, 'DD set for appt.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Jackson', 'Turner', (SELECT id FROM labs WHERE name='Vivera'), 'Retainer', CURRENT_DATE - 18, CURRENT_DATE + 1, CURRENT_DATE - 2, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Scarlett', 'Morris', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Aligners', CURRENT_DATE - 19, CURRENT_DATE + 2, CURRENT_DATE - 3, NULL, 'Followed up with lab.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'David', 'Martin', (SELECT id FROM labs WHERE name='Invisalign'), 'Space Maintainer', CURRENT_DATE - 8, CURRENT_DATE + 5, CURRENT_DATE + 2, NULL, 'Rush case.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Riley', 'Wilson', (SELECT id FROM labs WHERE name='AOA'), 'Hawley Retainer', CURRENT_DATE - 9, CURRENT_DATE + 6, CURRENT_DATE, NULL, 'Lab running behind.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Liam', 'Harris', (SELECT id FROM labs WHERE name='Vivera'), 'Bonded Retainer', CURRENT_DATE - 6, CURRENT_DATE + 28, CURRENT_DATE + 25, NULL, 'Replacement for lost retainer.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Isabella', 'King', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Nightguard', CURRENT_DATE - 2, CURRENT_DATE + 29, CURRENT_DATE + 26, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Alexander', 'Hill', (SELECT id FROM labs WHERE name='Invisalign'), 'Herbst', CURRENT_DATE - 3, CURRENT_DATE + 18, CURRENT_DATE + 15, NULL, 'Refinement scan sent.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Emily', 'Evans', (SELECT id FROM labs WHERE name='AOA'), 'Expander', CURRENT_DATE - 21, CURRENT_DATE - 4, CURRENT_DATE - 6, CURRENT_DATE - 7, 'Confirm fit at delivery.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Owen', 'Flores', (SELECT id FROM labs WHERE name='Vivera'), 'Retainer', CURRENT_DATE - 22, CURRENT_DATE - 5, CURRENT_DATE - 7, CURRENT_DATE - 9, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Grace', 'Cooper', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Aligners', CURRENT_DATE - 27, CURRENT_DATE - 7, CURRENT_DATE - 11, CURRENT_DATE - 6, 'Patient out of town until next week.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Luke', 'Davis', (SELECT id FROM labs WHERE name='Invisalign'), 'Space Maintainer', CURRENT_DATE - 22, CURRENT_DATE + 2, CURRENT_DATE - 6, NULL, 'DD set for appt.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Olivia', 'White', (SELECT id FROM labs WHERE name='AOA'), 'Hawley Retainer', CURRENT_DATE - 23, CURRENT_DATE + 3, CURRENT_DATE - 7, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'James', 'Allen', (SELECT id FROM labs WHERE name='Vivera'), 'Bonded Retainer', CURRENT_DATE - 10, CURRENT_DATE + 7, CURRENT_DATE, NULL, 'Followed up with lab.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Amelia', 'Nelson', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Nightguard', CURRENT_DATE - 11, CURRENT_DATE + 8, CURRENT_DATE + 1, NULL, 'Rush case.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Matthew', 'Phillips', (SELECT id FROM labs WHERE name='Invisalign'), 'Herbst', CURRENT_DATE - 6, CURRENT_DATE + 26, CURRENT_DATE + 23, NULL, 'Lab running behind.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Avery', 'Stewart', (SELECT id FROM labs WHERE name='AOA'), 'Expander', CURRENT_DATE - 2, CURRENT_DATE + 27, CURRENT_DATE + 24, NULL, 'Replacement for lost retainer.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'John', 'Peterson', (SELECT id FROM labs WHERE name='Vivera'), 'Retainer', CURRENT_DATE - 3, CURRENT_DATE + 28, CURRENT_DATE + 25, NULL, '', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Penelope', 'Brown', (SELECT id FROM labs WHERE name='Angel Aligners'), 'Aligners', CURRENT_DATE - 25, CURRENT_DATE - 4, CURRENT_DATE - 8, CURRENT_DATE - 10, 'Refinement scan sent.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Isaac', 'Jackson', (SELECT id FROM labs WHERE name='Invisalign'), 'Space Maintainer', CURRENT_DATE - 20, CURRENT_DATE - 5, CURRENT_DATE - 5, CURRENT_DATE - 5, 'Confirm fit at delivery.', now());
INSERT INTO appliances (id, patient_first_name, patient_last_name, lab_id, appliance_type, date_sent, delivery_date, expected_return_date, received_date, notes, updated_at) VALUES (gen_random_uuid()::text, 'Sophia', 'Young', (SELECT id FROM labs WHERE name='AOA'), 'Hawley Retainer', CURRENT_DATE - 25, CURRENT_DATE - 5, CURRENT_DATE - 9, CURRENT_DATE - 6, '', now());
